#!/bin/bash
# NFO Generator for music video files in Kodi
# This script depends on your media files having the correct media tags. Such as Title Artist Album.
# Puddletag is my preferred batch tagging tool for mp3 mp4 files

#File extension type mp3 mp4 ...etc
EXT=mp4

# Colors
red=$(tput setaf 1)
reset=$(tput sgr0)

# Requirements Check

REQUIRES="mediainfo xmlstarlet"

# Check that required tools are installed
for tool in ${REQUIRES}; do
    if ! [ -x "$(command -v ${tool})" ]; then
        printf "%b\n" ${red}  "Error: ${tool} is not installed or not in your path. ${tool} is required.${reset}\n" >&2
        exit 1
    fi
done

function NFO_GEN(){
Counter=0
Total=$(ls -l *."${EXT}" | wc -l)
for i in *."${EXT}"
do
((Counter="${Counter}"+1))
    mapfile -t -O 1 < <(mediainfo '--Output=General;%Title%,%Track/Position%,%Album%,%Artist%' "${i}" | awk -F'[,]' '{print $1;print $2;print $3;print $4}') values;
	New_Name=$(basename -s "${EXT}" "${i}");
	printf "%b" "File ${Counter} of ${Total} ${New_Name}nfo\n"
	xmlstarlet ed -u "/musicvideo/title" -v "${values[1]}" nfo-Template.nfo > "${New_Name}"nfo;
	xmlstarlet ed --inplace -u "/musicvideo/track" -v "${values[2]}" -u "/musicvideo/album" -v "${values[3]}" -u "/musicvideo/artist" -v "${values[4]}" "${New_Name}"nfo;
	
done
rm nfo-Template.nfo
}

# Create the NFO Template file
cat << EOF > nfo-Template.nfo
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<musicvideo>
    <title></title>
    <artist></artist>
    <track></track>
    <album></album>
    <userrating></userrating>
    <top250></top250>
    <outline></outline>
    <plot></plot>
    <tagline></tagline>
    <runtime></runtime>
    <mpaa></mpaa>
    <playcount></playcount>
    <lastplayed></lastplayed>
    <id></id>
    <genre></genre>
    <director></director>
    <premiered></premiered>
    <year></year>
    <status></status>
    <code></code>
    <aired></aired>
    <studio></studio>
    <trailer></trailer>
    <dateadded></dateadded>
    <fileinfo>
        <streamdetails>
            <video>
                <codec></codec>
                <aspect></aspect>
                <width></width>
                <height></height>
                <durationinseconds></durationinseconds>
                <stereomode></stereomode>
            </video>
            <audio>
                <codec></codec>
                <language></language>
                <channels></channels>
            </audio>
        </streamdetails>
    </fileinfo>
    <resume>
        <position></position>
        <total></total>
    </resume>
</musicvideo>
EOF
NFO_GEN
